### ISSUE TITLE
slf4j error

### ISSUE THREAD

**Issue by ansoncfit** [conveyal/geom2gtfs#25]
I've seen this and have heard reports of it from multiple other users:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/impl/StaticLoggerBinder
at org.slf4j.LoggerFactory.getSingleton(LoggerFactory.java:189)
at org.slf4j.LoggerFactory.bind(LoggerFactory.java:112)
at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:105)
at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:235)
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:208)
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:221)
at org.onebusaway.csv_entities.schema.AbstractEntitySchemaFactoryImpl.<clinit>(AbstractEntitySchemaFactoryImpl.java:44)
at org.onebusaway.csv_entities.CsvEntityWriter.<init>(CsvEntityWriter.java:28)
at org.onebusaway.gtfs.serialization.GtfsWriter.<init>(GtfsWriter.java:44)
at com.conveyal.geom2gtfs.Main.main(Main.java:96)
at com.conveyal.geom2gtfs.Main.main(Main.java:50)
Caused by: java.lang.ClassNotFoundException: org.slf4j.impl.StaticLoggerBinder
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 11 more
```

**Comment by mattwigway** [comment]
Try adding ```
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <version>1.1.3</version>
    </dependency>```

to the dependencies section of your pom.xml.

**Comment by ansoncfit** [comment]
Thanks, works smoothly now!
