### ISSUE TITLE
Maven compilation error 

### ISSUE THREAD

**Issue by ayesharshahid** [conveyal/geom2gtfs#27]
When I load the maven package, it gives me a compilation error as: 

"Failed to execute goal org.apache.maven.plugins: maven-compiler-plugin: 3.1: compile <default-compile> on project geom2gtfs: Compilation failure: 
[ERROR] .../geom2gtfs/ClusterStopGenerator.java: [192,72] cannot find symbol" 

Is this a version problem or related to changes in the source code? I ran the same code earlier and it was working fine.

**Comment by linkstatic12** [comment]
same

**Comment by squildweb** [comment]
Same problem here.

I already try use other Maven and JDE version, but nothing solve the problem for me.

If someone has an idea, please tell us.

**Comment by muddaserahmed** [comment]
I believe its a problem with the latest project itself not your environment. Try running a previous version from the commits and it should work.

**Comment by ayesharshahid** [comment]
This previous version worked for me: https://github.com/conveyal/geom2gtfs/tree/604fc36d2f98b1bbbee16fce6e2807457c12f8c2

**Comment by squildweb** [comment]
Thank you @muddaserahmed and @ayesharshahid i will try that and post if worked for me.

**Comment by squildweb** [comment]
@muddaserahmed and @ayesharshahid the version that you posted worked for me too, no more compilation errors.

But I have a question if some of you can help me I appreciate. In the last step when the program go write the files for me, this error appears:

writing to data/df.zip
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/impl/StaticLoggerBinder
	at org.slf4j.LoggerFactory.getSingleton(LoggerFactory.java:189)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:112)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:105)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:235)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:208)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:221)
	at org.onebusaway.csv_entities.schema.AbstractEntitySchemaFactoryImpl.<clinit>(AbstractEntitySchemaFactoryImpl.java:44)
	at org.onebusaway.csv_entities.CsvEntityWriter.<init>(CsvEntityWriter.java:28)
	at org.onebusaway.gtfs.serialization.GtfsWriter.<init>(GtfsWriter.java:44)
	at com.conveyal.geom2gtfs.Main.main(Main.java:96)
	at com.conveyal.geom2gtfs.Main.main(Main.java:50)
Caused by: java.lang.ClassNotFoundException: org.slf4j.impl.StaticLoggerBinder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more

I wrote something wrong in config or is anything else?

Thank you all.

Rafael Oliveira

**Comment by rafidmorshedi** [comment]
Hi Rafael,

I got the same error as you did in when writing files.

Would you be able to share how you solved the problem.

My error log is below.

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/impl/StaticLoggerBinder
        at org.slf4j.LoggerFactory.getSingleton(LoggerFactory.java:189)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:112)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:105)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:235)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:208)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:221)
        at org.onebusaway.csv_entities.schema.AbstractEntitySchemaFactoryImpl.<clinit>(AbstractEntitySchemaFactoryImpl.java:44)
        at org.onebusaway.csv_entities.CsvEntityWriter.<init>(CsvEntityWriter.java:28)
        at org.onebusaway.gtfs.serialization.GtfsWriter.<init>(GtfsWriter.java:44)
        at com.conveyal.geom2gtfs.Main.main(Main.java:96)
        at com.conveyal.geom2gtfs.Main.main(Main.java:50)
Caused by: java.lang.ClassNotFoundException: org.slf4j.impl.StaticLoggerBinder
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 11 more

**Comment by rajbhagatt** [comment]
I am also facing the same error!

**Comment by squildweb** [comment]
Sure @rafidmorshedi and @rajbhagatt.

If I remember correctly. I just add an repository and an dependency to the POM file.

Try use this file attached as your pom.xml.

Should work.

[pom.txt](https://github.com/conveyal/geom2gtfs/files/445572/pom.txt)

**Comment by rajbhagatt** [comment]
That worked!! 
Thanks @squildweb
